# Generated by Django 6.0.6 on 2026-06-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(db_index=True, max_length=10)),
                ('direction', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('entry_price', models.FloatField()),
                ('sl_price', models.FloatField()),
                ('tp_price', models.FloatField()),
                ('lot_size', models.FloatField()),
                ('result', models.CharField(choices=[('WIN', 'Win'), ('LOSS', 'Loss'), ('BE', 'Breakeven'), ('OPEN', 'Open')], default='OPEN', max_length=4)),
                ('pnl', models.FloatField(blank=True, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='trade_screenshots/')),
                ('notes', models.TextField(blank=True)),
                ('trade_score', models.IntegerField(blank=True, null=True)),
                ('session', models.CharField(blank=True, max_length=20)),
                ('trend_direction', models.CharField(blank=True, max_length=10)),
                ('mt5_ticket', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('drawings', models.ManyToManyField(blank=True, related_name='trades', to='market.chartdrawing')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
