# Generated by Django 6.0.6 on 2026-06-23 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('trade_score', 'Trade Score Threshold'), ('pattern_match', 'Pattern Match'), ('news_warning', 'News Warning'), ('price_level', 'Price Level Hit'), ('mt5_disconnect', 'MT5 Disconnected')], max_length=20)),
                ('pair', models.CharField(blank=True, max_length=10)),
                ('message', models.TextField()),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='ChartDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(db_index=True, max_length=10)),
                ('timeframe', models.CharField(max_length=5)),
                ('tool_type', models.CharField(choices=[('trendline', 'Trendline'), ('horizontal', 'Horizontal Line'), ('fibonacci', 'Fibonacci Retracement'), ('rectangle', 'Rectangle Zone'), ('ray', 'Ray'), ('pitchfork', 'Pitchfork'), ('text', 'Text Label'), ('pricerange', 'Price Range')], max_length=20)),
                ('coordinates', models.JSONField()),
                ('color', models.CharField(default='#2196F3', max_length=20)),
                ('thickness', models.IntegerField(default=2)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=5)),
                ('event_name', models.CharField(max_length=200)),
                ('time', models.DateTimeField(db_index=True)),
                ('importance', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('actual', models.CharField(blank=True, max_length=50)),
                ('forecast', models.CharField(blank=True, max_length=50)),
                ('previous', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='PatternTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pair', models.CharField(max_length=10)),
                ('timeframe', models.CharField(max_length=5)),
                ('price_sequence', models.JSONField()),
                ('lookback_candles', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_risk_pct', models.FloatField(default=1.0)),
                ('default_pairs', models.JSONField(blank=True, default=list)),
                ('score_weights', models.JSONField(blank=True, default=dict)),
                ('swing_lookback', models.IntegerField(default=5)),
                ('alert_sound', models.BooleanField(default=True)),
                ('alert_browser', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'User settings',
            },
        ),
        migrations.CreateModel(
            name='CandleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(db_index=True, max_length=10)),
                ('timeframe', models.CharField(db_index=True, max_length=5)),
                ('time', models.DateTimeField(db_index=True)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-time'],
                'unique_together': {('pair', 'timeframe', 'time')},
            },
        ),
        migrations.CreateModel(
            name='PatternOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found_at', models.DateTimeField()),
                ('similarity_score', models.FloatField()),
                ('outcome_pips', models.FloatField()),
                ('outcome_direction', models.CharField(max_length=10)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='market.patterntemplate')),
            ],
            options={
                'ordering': ['-found_at'],
            },
        ),
    ]
